baseURL: "https://blog.hellowood.dev"
title: HelloWood
theme: gokarna
license: MIT
languageCode: "cn"
defaultContentLanguage: "cn"
enableEmoji: true
enableRobotsTXT: true
pygmentsStyle: "doom-one"
description: "HelloWood Note"
homepage: "https://blog.hellowood.dev"
googleAnalytics: G-3MSGPYTHPZ

params:
  footer: "hellowood.dev"
  description: "Copy Paste Worker"
  avatarURL: "/images/avatar.webp"
  favicon: favicon.ico
  AvatarAltText: "avatar"
  avatarSize: "size-m"
  dateFormat: "2006-01-01"
  showPostsOnHomePage: "recent"
  ShowBackToTopButton: true
  socialIcons:
    - name: "github"
      url: "https://github.com/helloworlde"
  metaKeywords: ["blog", "hugo"]
  customHeadHTML: |
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <!-- Umami -->
    <script defer src="https://umami.hellowood.dev/script.js" data-website-id="7a9034de-0ce7-4756-942a-829e6cd22301"></script>
    <script defer src="https://cloud.umami.is/script.js" data-website-id="73ff1c8c-9938-43cf-81af-e77e26b0cca3"></script>
    <!-- Cloudflare -->
    <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "b2e481d136dc428c8c96c8673e2a04cf"}'></script>
    <!-- Google AdSense -->
    <meta name="google-adsense-account" content="ca-pub-3401351766168985">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3401351766168985" crossorigin="anonymous"></script>
    <!-- Microsoft Clarity -->
    <script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "jtbhx98g62");
    </script>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-3MSGPYTHPZ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-3MSGPYTHPZ');
    </script>
  customCommentHTML: |
    <script src="https://utteranc.es/client.js"
        repo="helloworlde/helloworlde.github.io"
        issue-term="title"
        theme="github-light"
        crossorigin="anonymous"
        async></script>

menu:
  main:
    - name: "Home"
      pre: "<span data-feather='home'></span>"
      url: "/"
      weight: 1
    - name: "Posts"
      pre: "<span data-feather='book'></span>"
      url: "/posts/"
      weight: 2
    - name: "Tags"
      pre: "<span data-feather='tag'></span>"
      url: "/tags/"
      weight: 3
    - identifier: "github"
      pre: "<span data-feather='github'></span>"
      url: "https://github.com/helloworlde"
      weight: 4
    - identifier: "dashboard"
      pre: "<span data-feather='pie-chart'></span>"
      url: "https://umami.hellowood.dev/share/lab/Blog"
      weight: 5
    - identifier: "rss"
      pre: "<span data-feather='rss'></span>"
      url: "/index.xml"
      weight: 6

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

enableGitInfo: true
frontmatter:
  date:
    - date
    - publishdate
    - pubdate
    - published
    - lastmod
    - modified
  lastmod:
    - lastmod
    - modified
    - date
    - publishdate
    - pubdate
    - published
  publishDate:
    - publishdate
    - pubdate
    - published
    - date